-- MySQL Script generated by MySQL Workbench
-- Wed Jan  4 18:45:34 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gymMan
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gymMan
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gymMan` DEFAULT CHARACTER SET utf8mb4 ;
USE `gymMan` ;

-- -----------------------------------------------------
-- Table `gymMan`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gymMan`.`user` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `creatorId` INT(10) UNSIGNED NOT NULL,
  `isActive` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
  `isDeleted` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `createDateTime` DATETIME GENERATED ALWAYS AS (now()) VIRTUAL,
  `email` VARCHAR(250) NOT NULL,
  `password` VARCHAR(250) NOT NULL,
  `firstName` VARCHAR(30) NOT NULL,
  `lastName` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_user_user_idx` (`creatorId` ASC) VISIBLE,
  CONSTRAINT `fk_user_user`
    FOREIGN KEY (`creatorId`)
    REFERENCES `gymMan`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gymMan`.`exercise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gymMan`.`exercise` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `creatorId` INT(10) UNSIGNED NOT NULL,
  `isActive` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
  `createDateTime` DATETIME NOT NULL DEFAULT now(),
  `name` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_exercise_user1_idx` (`creatorId` ASC) VISIBLE,
  CONSTRAINT `fk_exercise_user1`
    FOREIGN KEY (`creatorId`)
    REFERENCES `gymMan`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gymMan`.`exerciseCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gymMan`.`exerciseCategory` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `creatorId` INT(10) UNSIGNED NOT NULL,
  `createDateTime` DATETIME NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_exerciseCategory_user1_idx` (`creatorId` ASC) VISIBLE,
  CONSTRAINT `fk_exerciseCategory_user1`
    FOREIGN KEY (`creatorId`)
    REFERENCES `gymMan`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gymMan`.`exerciseImage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gymMan`.`exerciseImage` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `isActive` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
  `creatorId` INT(10) UNSIGNED NOT NULL,
  `createDateTime` DATETIME NOT NULL,
  `filePath` VARCHAR(1024) NOT NULL,
  `fileDescription` VARCHAR(2048) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `filePath` USING HASH (`filePath`) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_exerciseImage_user1_idx` (`creatorId` ASC) VISIBLE,
  CONSTRAINT `fk_exerciseImage_user1`
    FOREIGN KEY (`creatorId`)
    REFERENCES `gymMan`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gymMan`.`lookupExerciseCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gymMan`.`lookupExerciseCategory` (
  `exerciseId` INT(10) UNSIGNED NOT NULL,
  `exerciseCategoryId` INT(10) UNSIGNED NOT NULL,
  INDEX `fk_lookupExerciseCategory_exercise1_idx` (`exerciseId` ASC) VISIBLE,
  INDEX `fk_lookupExerciseCategory_exerciseCategory1_idx` (`exerciseCategoryId` ASC) VISIBLE,
  CONSTRAINT `fk_lookupExerciseCategory_exercise1`
    FOREIGN KEY (`exerciseId`)
    REFERENCES `gymMan`.`exercise` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lookupExerciseCategory_exerciseCategory1`
    FOREIGN KEY (`exerciseCategoryId`)
    REFERENCES `gymMan`.`exerciseCategory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gymMan`.`lookupExerciseImage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gymMan`.`lookupExerciseImage` (
  `exerciseId` INT(10) UNSIGNED NOT NULL,
  `imageId` INT(10) UNSIGNED NOT NULL,
  `sortOrder` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  INDEX `fk_lookupExerciseImage_exercise1_idx` (`exerciseId` ASC) VISIBLE,
  INDEX `fk_lookupExerciseImage_exerciseImage1_idx` (`imageId` ASC) VISIBLE,
  CONSTRAINT `fk_lookupExerciseImage_exercise1`
    FOREIGN KEY (`exerciseId`)
    REFERENCES `gymMan`.`exercise` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lookupExerciseImage_exerciseImage1`
    FOREIGN KEY (`imageId`)
    REFERENCES `gymMan`.`exerciseImage` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gymMan`.`routine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gymMan`.`routine` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `creatorId` INT(10) UNSIGNED NOT NULL,
  `createDateTime` DATETIME NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(1024) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_routine_user1_idx` (`creatorId` ASC) VISIBLE,
  CONSTRAINT `fk_routine_user1`
    FOREIGN KEY (`creatorId`)
    REFERENCES `gymMan`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gymMan`.`routineLookup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gymMan`.`routineLookup` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `exerciseId` INT(11) UNSIGNED NOT NULL,
  `routineId` INT(10) UNSIGNED NOT NULL,
  `creatorId` INT(11) UNSIGNED NOT NULL,
  `sortOrder` INT(11) UNSIGNED NOT NULL,
  `createDateTime` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_routineLookup_routine1_idx` (`routineId` ASC) VISIBLE,
  INDEX `fk_routineLookup_user1_idx` (`creatorId` ASC) VISIBLE,
  CONSTRAINT `fk_routineLookup_routine1`
    FOREIGN KEY (`routineId`)
    REFERENCES `gymMan`.`routine` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_routineLookup_user1`
    FOREIGN KEY (`creatorId`)
    REFERENCES `gymMan`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
gymMan